services:
  calimali-db:
    image: postgres@sha256:cf78e76683b9ca8c5733cbbdce6c9262b45b6767934dd0a95e671f9a0fc20685  # postgres:16-alpine, pinned 2026-09-10
    container_name: calimali-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - calimali_db:/var/lib/postgresql/data
    networks:
      - homelab
    ports:
      - "5433:5432"

  calimali-api:
    image: ghcr.io/malishn22/calimali-backend:latest
    container_name: calimali-api
    restart: unless-stopped
    environment:
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__Default: Host=${DB_HOST};Port=${DB_PORT};Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
      JWT_KEY: ${JWT_KEY}
      AUTH_USERNAME: ${AUTH_USERNAME}
      AUTH_PASSWORD: ${AUTH_PASSWORD}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_AUDIENCE: ${JWT_AUDIENCE}
      JWT_EXPIRY_DAYS: ${JWT_EXPIRY_DAYS}
    ports:
      - "8080:8080"
    networks:
      - homelab
    depends_on:
      - calimali-db

networks:
  homelab:
    external: true

volumes:
  calimali_db:
