services:

  ghms-backend:
    image: ghcr.io/malishn22/minecraft-backend:latest
    container_name: ghms-backend
    restart: unless-stopped
    ports:
      - "8000:8000"

  ghms-frontend:
    image: ghcr.io/malishn22/minecraft-frontend:latest
    container_name: ghms-frontend
    restart: unless-stopped
    ports:
      - "3010:80"
    depends_on:
      - ghms-backend